server:
  port: 8082
spring:
  application:
    name: VidPlay
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/contentdb
    username: postgres
    password: 4ie
